### ISSUE TITLE
Responsive design/constraints?

### ISSUE THREAD

**Issue by henningms** [Nets-mobile-acceptance/Netaxept-iOS-SDK#11]
Hi there!

Would it be possible to make the PiA SDK ViewControllers more responsive in terms of height? We would love to present these with a custom height instead of a full screen presentation. Would it also then be possible to wrap things in a scrollview? 

Thanks!

**Comment by Miss-PiA** [comment]
Hi, most of the view controllers are currently wrapped in a navigation controller. There is no direct API to customize properties like the view's height but you may try to add the controller as a child controller and control the height of its container view. We have a plan to provide view components instead of view controllers in the future which would be possible/easier to add in superviews such as a scroll view. Stay tuned and feel free to reach us if you face any challenge integrating our SDK!

**Comment by henningms** [comment]
We tried that, but the "Cancel" button etc stopped working, and since there's no scrollview in the PiA view controllers there was some hiccups as well. So it almost worked perfectly. 

Ooh, View components would be even better. Do you have a timeline for when we could expect a release/preview of those?

Thanks!
