### ISSUE TITLE
PiaSDK.launchWalletApp redirectWithoutInterruption is executed in a batch as much times as you open Mobile Pay without successful payment

### ISSUE THREAD

**Issue by zedkom** [Nets-mobile-acceptance/Netaxept-iOS-SDK#35]
hello.
I'm trying an interesting case with opening Mobile Pay from PiaSDK and switching back to the app multiple times without payment. In the last try when you actually do the payment redirectWithoutInterruption callback will be executed multiple times immediately (the count is the same number as your tries of opening the Mobile Pay app). 

steps:
I open Mobile Pay from the `PiaSDK.launchWalletApp`, after Mobile Pay is opened I go back to my app manually. Did it 4 times and on the last try I did a payment.

I have only 1 instance of my manager class that uses PiaSDK. All callbacks are covered with [weak self] and I don't have any method's local parameters captured by closures.
For testing purposes, I did it 4 times and on the last try, I did a successful payment.

**THE ISSUE:** 
`redirectWithoutInterruption` callback is executed 4 times immediately when I do the successful payment.

Here are my logs with comments inside "//":
```
// opening the Mobile Pay with PiaSDK.launchWalletApp, the log is created inside the walletURLCallback callback.
1. walletURLCallback executed, Mobile Pay app is opened, Time: 16:46:45.6580

// returned manually without accepting the payment.
1. redirectWithoutInterruption callback result: false, Time: 16:47:00.1800

// did the same a few times as on the previous steps.
2. walletURLCallback executed, Mobile Pay app is opened, Time: 16:47:49.5260
2. redirectWithoutInterruption callback result: false, Time: 16:47:55.7850

3. walletURLCallback executed, Mobile Pay app is opened, Time: 16:48:09.8780
3. redirectWithoutInterruption callback result: false, Time: 16:48:24.4300

// on the 4th try, I did the payment and was auto-redirected to my app.
4. walletURLCallback executed, Mobile Pay app is opened, Time: 16:48:34.2280

// milliseconds are almost the same for all 4 redirects.
4. redirectWithoutInterruption callback result: true, Time: 16:49:00.6450
4. redirectWithoutInterruption callback result: true, Time: 16:49:00.6470
4. redirectWithoutInterruption callback result: true, Time: 16:49:00.6500
4. redirectWithoutInterruption callback result: true, Time: 16:49:00.6510
```

Netaxept pod version - 2.5.0
Mobile Pay app version - 5.12.0.2558893

**Comment by Miss-PiA** [comment]
Hi @zedkom ,

Thanks for your report! 

The 4 continous redirect callbacks are **NOT** expected behavior and we will investigate from our end to fix this corner case. 

In practise, SDK is only the faciliator for redirect(app switching) between your merchant and wallet apps and the wallet transaction status is agnostic for SDK. Because Mobile wallet app doesn't share the transaction status to SDK after redirecting thru either manually or auto app switch case, which means SDK doesn't know the app switching is intentionally or not. For this reason, we recommend in the documentation to handle the wallet payment interruption cases at the first place once you received the false result from redirectWithoutInterruption callback.  Please kindly check the tips below:

Wallet payments - Cases of interrupted transactions
The typical payment flow via mobile wallets starts from the app where transaction registration request is sent to merchant backend. Upon receiving a wallet URL, the SDK launches the wallet app. The wallet app then redirects back to the application and PiaSDK notifies the associated wallet payment delegate to complete the transaction.

However, 

- User may interrupt this flow e.g. by manually navigating to your application before completing authorization at the wallet app or 
- The wallet app may fail to redirect for an unknown reason forcing the user to manually return to your application
In these and related scenarios, PiaSDK notifies interruption through in the callback redirectWithoutInterruption by returning false:

Upon receiving interruption, it’s best to query the transaction status and check if the authorization was complete or has been interrupted/denied in the wallet app. (If the user navigates back to the wallet app for authorization resulting in a successful redirect to your app, PiaSDK will notify the redirect where the app can commit / rollback the transaction accordingly)

**Comment by zedkom** [comment]
thanks @Miss-PiA , will follow your suggestions.
