### ISSUE TITLE
Warning: NPIError is deprecated

### ISSUE THREAD

**Issue by andreas-bakriemer** [Nets-mobile-acceptance/Netaxept-iOS-SDK#38]
Am I holding it wrong, or could the next release possible be rid of this warning:

<img width="606" alt="Screenshot 2022-04-20 at 20 02 58" src="https://user-images.githubusercontent.com/93766155/164294405-bae01058-b5fb-4f9e-8257-c1843c366871.png">

**Comment by BuildManager-Nets** [comment]
Yes, the error type NPIError will be removed. The warning is there to inform that the error type will be replaced with better error types that are specific to different payment methods. You can ignore the warning until this type is completely removed from our SDK.

**Comment by andreas-bakriemer** [comment]
Updated to version 2.7.0, warning is still there. It's the only warning in the project I am working on, so I would *really* like to see it disappear 😍

**Comment by Miss-PiA** [comment]
Hi @andreas-bakriemer ,
Unfortunately this issue will present in all the 2.X.X versions. We will resolve this issue in major release 3.X.

Thanks,

**Comment by casperriboe** [comment]
> We will resolve this issue in major release 3.X.

@Miss-PiA  Any hint for when this 3.x is out? Weeks, months, year?

**Comment by Miss-PiA** [comment]
Hi @casperriboe ,

According to our estimation, SDK v3.0.0 for Android will be release at first at around Q2 2023 and iOS v3.0.0 will follow afterward. We will keep updating once the release date of version 3.0.0 is confirmed later. Please let us know if you have any further questions.

**Comment by casperriboe** [comment]
Thanks a lot for the estimated release, good to know 👍🏻

**Comment by andreas-bakriemer** [comment]
We're approaching the end of Q2 - how does it look for the Android release, and the expectations for iOS?

**Comment by BuildManager-Nets** [comment]
Hi Andreas,
We are working on it and we will update you on the same.
Thanks

**Comment by casperriboe** [comment]
We're halfway through Q3 now. How are those estimations looking?
The issue is still not resolved, so this issue should not be closed.

**Comment by Miss-PiA** [comment]
Hi @casperriboe ,

Unfortunately, we are full speed on building mobile SDK v3 from scratch in the new programming language Swift/Kotlin as well as new UI framework like jetpack-compose and swiftUI. With that, the whole development effort are quite intensive to catch up with all capabilities and features SDK v2 supported. Our anticipation is that we will offer Android SDK v3 at very beginning at around Q4.23-Q1.24, and then iOS SDK v3 will deliver after Android SDK v3. Regarding this specific warning message, we will not fix in SDK v2 but in SDK v3 and the public API will entirely redesign so that there won't be deprecation warning any more. If you want to try the early beta version of SDK v3, please drop us email [in-app-support@nets.eu](mailto:in-app-support@nets.eu)  and we could potentially select suitable candidates to test v3 once we have sharable SDK. We will keep you posted once the public release is ready!

**Comment by casperriboe** [comment]
Thank you for the detailed status.
