### ISSUE TITLE
SDK time out when issuer does not reply

### ISSUE THREAD

**Issue by andreas-bakriemer** [Nets-mobile-acceptance/Netaxept-iOS-SDK#51]
I have had a couple of incidents, where a customer tries to create a card. The process appears to just stop somewhere in the SDK.

Talking to Netaxept support about the transaction, it appears that the issuer fails to respond to Netaxept requests, and the whole process just halts with a spinner on the SDK.

How about letting the SDK timeout, and report the error in some form? I think the Netaxept supporters I have been engaging would really appreciate that, as well as the customer wanting to create a card.

Thanks 🙏

**Comment by BuildManager-Nets** [comment]
Hi Andreas,

Actually, whenever there is the issuer fails to respond to Netaxept requests means the issue is blocked in the 3DS authentication phase.
The 3DS process is handled by card issuers/Banks which is out of our SDK control and we can’t intervene. In this scenario, the user can click the “X” button in our SDK to cancel the transaction and re-attempt the transaction again.
In case of any issue please let us know.

Thanks.

**Comment by andreas-bakriemer** [comment]
So I am guessing that "the issuer fails to respond to Netaxept requests" doesn't mean that Netaxept SDK is actively requesting anything that issuer fails to respond to, but rather that Netaxept SDK is waiting for some callback or whatever. Needless to say, that shouldn't be interrupted 🤝
